
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#smartir:

#remote:
#  - platform: xiaomi_miio
#    host: 192.168.1.165
#    token: a371a38255fcbb2b2cd395ec0acf3ef0

#climate:
#    platform: smartir
#    name: аниме
#    unique_id: smart_way
#    device_code: 1540
#    controller_data: remote.xiaomi_miio_192_168_1_165